#!/bin/sh

# by Jaroslav Vitku [vitkujar@fel.cvut.cz]

# This script installs standalone Nengo by means of Gradle. 
# Note that this compilation requires rosjava_core installed in ~/.m2/repository , e.g.:
#   cd ../ && git clone https://github.com/rosjava/rosjava_core.git && git checkout hydro-devel && ./gradlew install
#   see: https://github.com/rosjava/rosjava_core
#
# 
# After downloading the project into your computer, run this script to install Nengo
#
# This script does:
#   -compiles Nengo and installs it into local maven repository (~/.m2/repository/)
#   -creates eclipse projects


echo "\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX "
echo "   XXXXXXXX Building the Nengo, generating eclipse projects.. "
echo "      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"

# bug in gradle generates duplicate entries if .classpath file exist:
if [ -f simulator/.classpath ]; then rm simulator/.classpath
fi
if [ -f simulator-ui/.classpath ]; then rm simulator-ui/.classpath
fi

# set this as parent multi-project for gradle
cp standalone.build.gradle build.gradle
cp standalone.settings.gradle settings.gradle

# note that you should edit these files build.gradle.* in order to change the settings!
cp simulator-ui/standalone.build.gradle simulator-ui/build.gradle
cp simulator/standalone.build.gradle simulator/build.gradle

# run tests?
TEST=0
if [ "$TEST" -eq "1" ]; then
    ./gradlew clean build install eclipse --continue
    echo "Authors of Nengo: \" If you see \"BUILD FAILED\" above and you are worried... relax!\" \"Its normal.\""
    echo "\"Moving right along...\""
else
    ./gradlew clean build install eclipse --continue -x test 
fi

rm build.gradle
rm settings.gradle

# removed so the user won't edit it..
rm simulator-ui/build.gradle
rm simulator/build.gradle

echo "\nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX "
echo "   XXXXXXXX All done "
echo "      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n"