#!/usr/bin/env bash
#
# Author Jaroslav Vitku [vitkujar@fel.cvut.cz] based on original nengo script. Launch the GUI.
# 


cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Old stuff, TODO link rosjava
#MY_PATH=../rosjava/lib/*:../rosjava/include/*:../simulator/lib/swingx-all-1.6.4.jar/
#PROJECTS=../testnodes/bin/:../../../simulators/vivae/bin/:../../../simulators/vivae/lib/*:../../../simulators/vivae/
#MODLELS_PATH=../../models/nengo/rbm-vision/

# TODO: link rosjava somewhere
#$APP_HOME/lib/rosjava-0.0.0-SNAPSHOT.jar
#$APP_HOME/lib/apache_xmlrpc_common-0.0.0-SNAPSHOT.jar:$APP_HOME/lib/apache_xmlrpc_client-0.0.0-SNAPSHOT.jar:
#$APP_HOME/lib/rosjava_bootstrap-0.0.0-SNAPSHOT.jar:$APP_HOME/lib/rosjava_messages-0.0.0-SNAPSHOT.jar:
#$APP_HOME/lib/apache_xmlrpc_server-0.0.0-SNAPSHOT.jar:

# TODO: GPU does not work so far
MY_GPU=../simulator/src/c/NengoGPU:../simulator/src/c/NengoUtilsGPU


# Copmared to gradle build (build/*) this links *.class files compiled by Eclipse into bin/ directory. 
# Note that projects MUST BE BUILT with Eclipse in order to this to run
# TODO unify this
CLASSES=python:bin:lib:../simulator/bin:../simulator/lib

APP_HOME=$PWD

# jar files under simulator-ui/lib
UI=$APP_HOME/lib/colt.jar:$APP_HOME/lib/commons-collections-3.2.jar:$APP_HOME/lib/itextpdf-5.3.4.jar:$APP_HOME/lib/jayatana-1.2.4.jar:$APP_HOME/lib/jbullet.jar:$APP_HOME/lib/jnumeric-0.1.jar:$APP_HOME/lib/jpct.jar:$APP_HOME/lib/jung-1.7.6.jar:$APP_HOME/lib/jython.jar:$APP_HOME/lib/macify-1.4.jar:$APP_HOME/lib/piccolo.jar:$APP_HOME/lib/piccolox.jar:$APP_HOME/lib/vecmath.jar:$APP_HOME/lib/formsrt.jar
# jar files under simulator/lib
SIM=$APP_HOME/../simulator/lib/log4j-1.2.16.jar:$APP_HOME/../simulator/lib/qdox-1.6.3.jar:$APP_HOME/../simulator/lib/Jama-1.0.2.jar:$APP_HOME/../simulator/lib/formsrt.jar:$APP_HOME/../simulator/lib/jcommon-1.0.0.jar:$APP_HOME/../simulator/lib/jfreechart-1.0.1.jar:$APP_HOME/../simulator/lib/jgrapht-jdk1.5-0.7.3.jar:$APP_HOME/../simulator/lib/jmatio.jar:$APP_HOME/../simulator/lib/ssj.jar:$APP_HOME/../simulator/lib/swingx-all-1.6.4.jar
# newly added jar files (copied from simulator-ui/build/install/simulator-ui/lib)
OTHER=$APP_HOME/lib/launch4j.jar:$APP_HOME/lib/commons-beanutils.jar:$APP_HOME/lib/commons-logging.jar:$APP_HOME/lib/forms.jar:$APP_HOME/lib/foxtrot.jar:$APP_HOME/lib/looks.jar:$APP_HOME/lib/xstream.jar:$APP_HOME/lib/hamcrest-core-1.1.jar:$APP_HOME/lib/junit-4.10.jar:$APP_HOME/lib/xml-apis-1.0.b2.jar:$APP_HOME/lib/ws-commons-util-1.0.1.jar:$APP_HOME/lib/commons-pool-1.6.jar:$APP_HOME/lib/jsr305-1.3.9.jar:$APP_HOME/lib/guava-12.0.jar:$APP_HOME/lib/netty-3.5.2.Final.jar:$APP_HOME/lib/dnsjava-2.1.1.jar:$APP_HOME/lib/com.springsource.org.apache.commons.net-2.0.0.jar:$APP_HOME/lib/com.springsource.org.apache.commons.lang-2.4.0.jar:$APP_HOME/lib/com.springsource.org.apache.commons.io-1.4.0.jar:$APP_HOME/lib/com.springsource.org.apache.commons.logging-1.1.1.jar:$APP_HOME/lib/com.springsource.org.apache.commons.codec-1.3.0.jar:$APP_HOME/lib/com.springsource.org.apache.commons.httpclient-3.1.0.jar



# I moved nengo sources from original folder to src/main/java (because of gradle), caused Log4 warnings..  
#LOG=../simulator/src/resources/

# new one: (more/less memory)
# java -Xms100m -Xmx800m -cp $THEIR_PATH:$MY_PATH:$MODLELS_PATH:$LOG:$PROJECTS ca.nengo.ui.NengoLauncher

echo $CLASSES
echo " \n"
echo $UI
echo " \n"
echo $SIM

#java -Xms300m -Xmx1600m -cp $COPIED:$PTH ca.nengo.ui.NengoLauncher
java -Xms300m -Xmx1600m -cp $CLASSES:$UI:$SIM:$OTHER ca.nengo.ui.NengoLauncher